import os
from .paths import CLASSIFICATION_DATASET_DIR, CLASSIFIER_MODEL_DIR

# Global Hyperparameters
IMAGE_SIZE = 224
BATCH_SIZE = 32
NUM_WORKERS = 4
EPOCHS = 15
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4

# Classification Config
NUM_CLASSES = 38
MODEL_NAME = "efficientnet_b0"

TRAIN_DIR = CLASSIFICATION_DATASET_DIR / "train"
VAL_DIR = CLASSIFICATION_DATASET_DIR / "val"
BEST_MODEL_PATH = CLASSIFIER_MODEL_DIR / "best_model.pth"
